import uuid, os, base64, json, requests, pathlib, time, boto3

def push_files_to_branch_and_open_pr(work_item, code_path, model_signature) -> tuple[str, str]:

  issue_key = work_item.get("key") or ""
  guid = uuid.uuid4()

  base_branch = _get_default_branch()
  base_sha = _get_ref_sha(base_branch)
  branch_name  = f"codegen/{issue_key}-{guid}"

  _create_branch(branch_name, base_sha)

  # walk files under root_dir and upload
  commit_message = "chore(codegen): add generated files"

  root = pathlib.Path(code_path)
  for p in root.rglob("*"):
    if p.is_file():
      rel = p.relative_to(root).as_posix()
      _put_file(branch_name, rel, p.read_bytes(), commit_message)

  pr_title = f"Codegen by {model_signature} for {issue_key}"
  pr_body = f"Generated by {model_signature}, processed by Lambda for {issue_key}"
  pr_url = _create_pr(branch_name, base_branch, pr_title, pr_body)
  return branch_name, pr_url


# def push_code_to_branch_and_open_pr(work_item, model_signature) -> tuple[str, str]:
#   issue_key = work_item.get("key") or ""
#   guid = uuid.uuid4()

#   base_branch = _get_default_branch()
#   base_sha = _get_ref_sha(base_branch)
#   branch_name  = f"coderev/{issue_key}-{guid}"

#   _create_branch(branch_name, base_sha)

#   # ship json containing raw code
#   commit_message = f"chore(coderev): add generated files {model_signature}"


def _get_default_branch() -> str:
  api, owner, repo, token = _get_envs()

  r = requests.get(f"{api}/repos/{owner}/{repo}", headers=_gh_headers(), timeout=30)
  r.raise_for_status()
  return r.json()["default_branch"]


def _get_ref_sha(branch: str) -> str:
  api, owner, repo, token = _get_envs()

  r = requests.get(f"{api}/repos/{owner}/{repo}/git/refs/heads/{branch}",
                    headers=_gh_headers(), timeout=30)
  r.raise_for_status()
  return r.json()["object"]["sha"]


def _create_branch(new_branch: str, base_sha: str):
  api, owner, repo, token = _get_envs()

  r = requests.post(f"{api}/repos/{owner}/{repo}/git/refs",
                    headers=_gh_headers(),
                    json={"ref": f"refs/heads/{new_branch}", "sha": base_sha},
                    timeout=30)

  if r.status_code == 422 and "Reference already exists" in r.text:
    return  # ok if it already exists

  r.raise_for_status()


def _put_file(branch: str, path: str, content_bytes: bytes, message: str):
  api, owner, repo, token = _get_envs()

  # Check if file exists to supply its SHA (required for updates)
  get = requests.get(
    f"{api}/repos/{owner}/{repo}/contents/{path}",
    headers=_gh_headers(),
    params={"ref": branch},
    timeout=30
  )

  sha = get.json().get("sha") if get.status_code == 200 else None

  payload = {
    "message": message,
    "content": base64.b64encode(content_bytes).decode("ascii"),
    "branch": branch,
  }

  if sha:
    payload["sha"] = sha

  put = requests.put(
    f"{api}/repos/{owner}/{repo}/contents/{path}",
    headers=_gh_headers(),
    json=payload,
    timeout=60
  )

  if put.status_code == 409 and "is binary and cannot be rendered" in put.text:
    # harmless; retry once
    time.sleep(0.5)
    put = requests.put(
      f"{api}/repos/{owner}/{repo}/contents/{path}",
      headers=_gh_headers(),
      json=payload,
      timeout=60
    )

    put.raise_for_status()


def _create_pr(head_branch: str, base_branch: str, title: str, body: str) -> str:
  api, owner, repo, token = _get_envs()

  r = requests.post(
    f"{api}/repos/{owner}/{repo}/pulls",
    headers=_gh_headers(),
    json={"title": title, "head": head_branch, "base": base_branch, "body": body},
    timeout=30
  )
  if r.status_code == 422 and "A pull request already exists" in r.text:
    # Find existing PR link
    lst = requests.get(
      f"{api}/repos/{owner}/{repo}/pulls",
      headers=_gh_headers(),
      params={"head": f"{owner}:{head_branch}", "state": "open"},
      timeout=30
    )
    if lst.status_code == 200 and lst.json():
      return lst.json()[0]["html_url"]
  r.raise_for_status()
  return r.json()["html_url"]


def _gh_headers():
  api, owner, repo, token = _get_envs()

  return {
    "Authorization": f"Bearer {token}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "lambda-codegen-push"
  }


def _get_envs():
  api = os.environ.get("GITHUB_API")
  owner = os.environ.get("GITHUB_OWNER")
  repo = os.environ.get("GITHUB_REPO")
  token = os.environ.get("GITHUB_TOKEN")

  return api, owner, repo, token

